#!/usr/bin/python3
"""
0. Pascal's Triangle
"""

def pascal_triangle(n):
    """This function prints integers representing Pascal's triangle
    of integers representing the Pascal’s triangle of n
    """

    res = []
    if n > 0:
        for i in range(1, n + 1):
            level = []
            c = 1
            for j in range(1, i + 1):
                level.append(c)
                c = c * (i - j) // j
            res.append(level)
     return res
